In [1]:
# Decision Tree Classification using ID3 Algorithm

import numpy as np
import pandas as pd

from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


def evaluate_classification(X, y, dataset_name):

    print("\n====================================")
    print("Dataset:", dataset_name)
    print("====================================")

    # Split dataset
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    # ID3 → entropy criterion
    model = DecisionTreeClassifier(criterion="entropy", random_state=42)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # Error Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1 Score:", f1)

    print("\nConfusion Matrix:")
    print(cm)


# Dataset 1: Iris
iris = load_iris()
evaluate_classification(iris.data, iris.target, "Iris Dataset")


# Dataset 2: Breast Cancer
cancer = load_breast_cancer()
evaluate_classification(cancer.data, cancer.target, "Breast Cancer Dataset")


Dataset: Iris Dataset
Accuracy: 0.9777777777777777
Precision: 0.9793650793650793
Recall: 0.9777777777777777
F1 Score: 0.9777448559670783

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]

Dataset: Breast Cancer Dataset
Accuracy: 0.9649122807017544
Precision: 0.9649541140481607
Recall: 0.9649122807017544
F1 Score: 0.9647902680643604

Confusion Matrix:
[[ 59   4]
 [  2 106]]


In [2]:
# Decision Tree Regression using CART Algorithm

import numpy as np

from sklearn.datasets import fetch_california_housing, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def evaluate_regression(X, y, dataset_name):

    print("\n====================================")
    print("Dataset:", dataset_name)
    print("====================================")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    # CART → squared_error criterion
    model = DecisionTreeRegressor(
        criterion="squared_error",
        random_state=42
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # Error Metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print("MAE:", mae)
    print("MSE:", mse)
    print("RMSE:", rmse)
    print("R2 Score:", r2)


# Dataset 1: California Housing
housing = fetch_california_housing()
evaluate_regression(housing.data, housing.target, "California Housing Dataset")


# Dataset 2: Diabetes
diabetes = load_diabetes()
evaluate_regression(diabetes.data, diabetes.target, "Diabetes Dataset")


Dataset: California Housing Dataset
MAE: 0.46904822189922485
MSE: 0.5280096503174904
RMSE: 0.7266427253592307
R2 Score: 0.5977192261218356

Dataset: Diabetes Dataset
MAE: 60.015037593984964
MSE: 5697.789473684211
RMSE: 75.48370336492647
R2 Score: -0.05547696148647652
